/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Aut o-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "FreeRTOSConfig.h"
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "defines.h"


#include "RCC_interface.h"
#include "GPIO_interface.h"


/**
 * @brief TASK	2		(Pre-emption)
 */
/* Define Tasks Priorities */
#define  LedOn_PRIORITY (2)

#define  LedOFF_PRIORITY (3)

/*tasks codes prototypes */
void LedOn_code( void* pvParamter);

void LedOFF_code( void* pvParamter);


/*Create Task Handles Create */
xTaskHandle Task1Hand = NULL;

xTaskHandle Task2Hand = NULL;


int main(void)
{
	RCC_voidSysClkInt();
	RCC_EnablePeripheralClk(RCC_AHB,IOPA_EN);

	/*initialize GPIO_LED_PIN*/
	GPIO_u8SetPinDirection(GPIO_A,GPIO_PIN5,GPIO_OUTPUT_PP);

	/*Create tasks*/
	xTaskCreate(LedOn_code,(const char *)"Task1",85,NULL,LedOn_PRIORITY,&Task1Hand);

	/*Create tasks*/
	xTaskCreate(LedOFF_code,(const char *)"Task2",85,NULL,LedOFF_PRIORITY,&Task2Hand);

	/*start Scheduler */
	vTaskStartScheduler();

	/*Never Enter Here */
	return 0;
}

void LedOn_code( void* pvParamter){

	for (;;)
	{
		/*Turn On  Led */
		GPIO_u8SetPinValue(GPIO_A,GPIO_PIN5,GPIO_HIGH);

	}
}
void LedOFF_code( void* pvParamter){

		vTaskDelay(2000);
		for (;;)
		{
			/*Turn Off Led */
			GPIO_u8SetPinValue(GPIO_A,GPIO_PIN5,GPIO_LOW);

		}
}


/*
 * if You Turn On Preemption Led will Be Off Always
 * if You Turn Off Preemtion will Be On Always
 *
 * **/

